### ISSUE TITLE
Technical deep dive kickoff - March 21 at AWS

### ISSUE THREAD

**Issue by nilesh1402** [vistadataproject/VAM2ProjectManagement#1]
Setup the technical deep dive meeting after March 15th in Washington DC

**Comment by rafael5** [comment]
Agenda is technical deep dive of VAM deployment in AWS.
Will be held at AWS HQ near Dulles Airport with technical team

**Comment by nilesh1402** [comment]
Plan a meeting with Conor/Mike/Tom for in person meeting , from AWS with Jim Jennis.

**Comment by rafael5** [comment]
Closing... this meeting has been scheduled and on track

**Comment by piyushthesia** [comment]
The issues is closed. However, adding the meeting notes link for future refrence:
 https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/weekly_meeting_minutes/Technical%20Deep%20Dive%20Meeting%20at%20AWS%20on%2003-21-2019.md
