### ISSUE TITLE
IOC Dashboard- create full task list and schedule

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#11]

**Comment by nilesh1402** [comment]
Updated IOC Process under IOC Folder as per discussion on 3/15 : https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/IOC/IOC%20Process

**Comment by piyushthesia** [comment]
Done. https://github.com/vistadataproject/VAM2ProjectManagement
