### ISSUE TITLE
AsciiDoc - Recommend for larger technical documentation [references]

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#12]
Github markdown is not designed for large or complex documents (i.e. it cannot auto-generate, nor maintain up-to-date a table of contents, footnotes, or a references)  nor does it have fully automated translation pipelines (to HTML, PDF, Word, etc) necessary for automated submission to the Government in these formats.

Therefore, for any documentation or reports that will be formally submitted to the government (including all PWS, ATO, and IOC documentation) the source document must be created and updated on Github using the Asciidoc markup language (using *.adoc  extension) and then use Pandoc (or similar tool)  to auto-generate the final fixed snapshots in HTML, Word, or PDF.

__Github native support of Asciidoc__
https://github.com/asciidoctor
https://asciidoctor.org/news/2013/01/30/asciidoc-returns-to-github/
https://asciidoctor.org/news/2014/02/04/github-asciidoctor-0.1.4-upgrade-5-things-to-know

__Ascciidoc User Guide__
http://asciidoc.org/index.html
http://asciidoc.org/userguide.html

__Installation on Mac/Windows__
https://asciidoctor.org/#b-homebrew-macos
https://asciidoctor.org/#c-windows

__Code editor plugins for live preview of Asciidoc__
__Atom__: https://atom.io/packages/asciidoc-preview
__JetBrains__: https://plugins.jetbrains.com/plugin/7391-asciidoc
__VisualCode__: https://marketplace.visualstudio.com/items?itemName=stayfool.vscode-asciidoc

__Examples TOC generation__
https://github.com/opendevise/asciidoc-samples/blob/master/article.adoc
https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74

__Example Diagrams creation__
https://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/

**Comment by piyushthesia** [comment]
I believe AsciiDocs is great for developers and testers BUT it may not be a solution for Converting Plans that are in MS Word.  Can we look at Pandoc for MS Word doc conversions pelase.

**Comment by mfuroyama** [comment]
@piyushthesia @rafael5 Just adding my $0.02 here: one advantage that a text-based format (like AsciiDoc) might have over a binary-ish one like MS Word is the fact that the document artifacts can be tracked, version-controlled and diff'd here, directly in GitHub. If I'm not mistaken, that's what Dr. Richards is aiming for (mostly due to contractual requirements)?

Either way, once we've agreed upon formats and document lists, and once we're going full-steam in the VAEC, I can help setup and spin up a CI-style pipeline (Jenkins? AWS Code Pipeline? etc.) using Pandoc or other tools required to do any auto-conversion necessary.

**Comment by rafael5** [comment]
Thank you Mike,

You are reading my mind!    This is precisely the reason for mandating (in
the PWS) that all documentation must created, managed, and version
controlled *in markdown*  and be managed in the same repository and
environment as all other technical artifacts so that everything - code,
data, documentaiton - is all version controlled continuously and in synch
at all times.

The reason for asciidoc is that Github-flavored markdown does not have any
advanced features required for creating larger documents (which
necessitates automation of generation a table of contents, index, and
footnotes, and more advance formatting).

So far in my investigation,  asciidoc seems the simplest of the more
advanced markdown languages, but I am open  to other markup (as Thesia
mentioned,  pandoc)  so long as the tradeoff of simplicy vs power is a good
one.

This is an active area of investigation, so again, if either of you have
first-hand experience using any of these alternatives to github markdown,
I'm all ears.

For now:
1. Thesia: project managers (or management team, like yourself)  will
continue to use Github Markdown, since you and Nilesh will then have a
single, simple, common method to manage all documents.
2. Mike: for developers: you guys will be auto-generating a LOT of reports
based on all your security monitoring and audits, and we want to have a
fully automated pipeline to generate whatever format the government wants
(mainly Word and PDF).  These will require more elaborate typesetting,
table of contents, etc.  And may be based off of templates we get from the
government (i.e what a standard security report should look like).  So
experiment away.  Don't waste your valuable developer time with this... but
its a back-burner thing we need to figure out...

RR




Rafael


*Rafael Richards MD MS*
*202-469-1527*

**Comment by rafael5** [comment]
> I believe AsciiDocs is great for developers and testers BUT it may not be a solution for Converting Plans that are in MS Word. Can we look at Pandoc for MS Word doc conversions pelase.

=> Asciidoc is for everyone who needs to write a document. It is not for 'developers only'. It is for nontechnical  managers who need to do 'agile documentation'.  Word is NOT agile. It is static, and instantly becomes stale, and is impossible to version control or collaborate with using any automation tools. 

=> The reason we are picking this is that is the simplest and easiest to use (next to github markdown).

**Comment by conorcaregraf** [comment]
just my two pence. I do think there's a difference __between Document and Web motifs__ and then there's the __VA's Word templates__. Also there's a categorical difference between GUI-edited (Word) with their non re-entrant quirks and ascii markups which are largely interchangeable. Types ...

\# | Description
--- | --- 
1 | standard VA documents which come in Word templates and end in Word documents
2 | project, user guides etc for which no VA template exists. It's up to us to write them and deliver them based on the particular direction we receive for VAM-2
3 | complete, exhaustive, encyclopedic inventories - ex/ all 5500+ RPCs, their descriptions and how we treat them. These would have accompanying summaries (type 4 documents) but a web rendering would be the master. Think back to when javadoc came along - no one dumps enormous APIs into Word docs. For these, the __Browser/Web__ motif is the target and maybe we do a "rollup" PDF.
4 | summary documents - ex/ progress/scope of RPC Interface Definition etc. These mix manual text and generated numbers/tables. There can be a web rendering but given size, a "document" works too.

I don't think we'd turn Type 1's out of Word only to go back to Word. I think you loose formatting if you leave a Word document no matter what you do - it's a quirky quirky format and GUI. Type 3 should NEVER be Word. The others - well, Word is at most a generated form and PDF would suffice for the "roll up print". 

Of course, maybe we have more ...

**Comment by rafael5** [comment]
closing for the moment... This is not a project management task per se... will address with technical team at later date
