### ISSUE TITLE
Obtain VAEC IOC Environments

### ISSUE THREAD

**Issue by piyushthesia** [vistadataproject/VAM2ProjectManagement#17]
Obtain / Configure VAEC IOC Environments for Build 4 Delivery

**Comment by rafael5** [comment]
Can you find out who will be do this for us?  Thx!

**Comment by nilesh1402** [comment]
@rafael5  We will get more clarity after our deep dive meeting on 21st.  My first thought will be you and Cheryl will help us identify the site ( like Palo Alto ) and then we need to follow up with AWS team on the migration timeline for VistA.

**Comment by nilesh1402** [comment]
@rafael5 based on our deep dive meeting, we are targetting Valley Coastal, TX and Oklahoma, OK.

**Comment by NishadShah** [comment]
IOC environment was reconfigured and pointed to VCB VISTA on VAEC. It was successfully demonstrated on 12/04/2019.
