### ISSUE TITLE
Dashboards - add "Due data / Done date / Approved date" columns to all dashboards

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#19]
It means nothing to have a document "done" if it is not approved by the ISO
Therefore, we need all dashboards to have columns for the following:
- Due date
- Done date (including uploaded to RV)
- Approved date (by ISO)

**Comment by piyushthesia** [comment]
Is the formatting for work completed (except for the date format style) as per your guidance?

**Comment by rafael5** [comment]
All dates for all Github dashboards and documentation

**Comment by piyushthesia** [comment]
Ok. 
Clarification:  We are also changing yyyy-mm-dd date format you suggested earlier for weekly and monthly reports?

**Comment by piyushthesia** [comment]
@rafael5  All Date updates done in all Dashboards and deliverables

**Comment by piyushthesia** [comment]
Done.
