### ISSUE TITLE
Create A&A checklist and schedule tracking on Github

### ISSUE THREAD

**Issue by nilesh1402** [vistadataproject/VAM2ProjectManagement#2]
Update A&A details on Github

**Comment by rafael5** [comment]
See: https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/ATO/ATO%20checklist.md

**Comment by rafael5** [comment]
This checklist will be used for tracking A&A completion for ATO

**Comment by rafael5** [comment]
This has been done here:
https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/README.md#ato-dashboard
