### ISSUE TITLE
ATO Action items from 03/13/2019 Meeting

### ISSUE THREAD

**Issue by nilesh1402** [vistadataproject/VAM2ProjectManagement#21]
1. Update description in Risk Vision for VAM2 Scope.
2. Cleanup Owner's list in Risk Vision ( Drop all personnel who are not part of VAM2)
3. Setup meeting with ISO and get permission to update RV questions.
4.  Complete the Gap Analysis for ATO dashboard.

**Comment by rafael5** [comment]
Please make each of these individual issues so you can track them.
Tag each of these issues as 'ATO' under the Labels (on right)
Tag Assignees to:  #davidfaulkner08  #piyushthesia #nilesh1402

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08   Done.  Four new issues created.

**Comment by piyushthesia** [comment]
All tasks were completed as directed.
