### ISSUE TITLE
Update ATO and IOC Dashboards:   ATO:  May 1, 2019;  IOC: October 1, 2019

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#22]
Dates of ATO and IOC are as follows:
* ATO:   May 1, 2019
* IOC:  October 1, 2019

*__please update all dates on ATO and IOC dashboards to reflect these target dates__*

**Comment by piyushthesia** [comment]
@rafael5  Done.  Though it is my understanding that some of the work will come in a waterfall.  I guess we will have to revisit each item (may be in the deep dive) and assign more appropriate target dates to each task.

**Comment by rafael5** [comment]
There is no waterfall in VAM.

* Everything will be done Agile
* All project management tasks shall be performed in parallel to the
maximum extent possible

**Comment by piyushthesia** [comment]
Understood. I commented based on the schedule dependencies of the tasks.  Will revisit the same internally.

**Comment by piyushthesia** [comment]
Updated ATO and IOC Dashboards.
