### ISSUE TITLE
Gap Analysis for ATO dashboard.

### ISSUE THREAD

**Issue by piyushthesia** [vistadataproject/VAM2ProjectManagement#26]

**Comment by rafael5** [comment]
Specifically:  
1. identify what is missing
2. identify what needs to be done next

**Comment by piyushthesia** [comment]
@rafael5 Please Review.

[VAM2 ATO Dashboard Gap Analysis.docx](https://github.com/vistadataproject/VAM2ProjectManagement/files/2978962/VAM2.ATO.Dashboard.Gap.Analysis.docx)

**Comment by piyushthesia** [comment]
@rafael5 Please review and advise.

https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/ATO/VAM2%20ATO%20Dashboard%20Gap%20Analysis.md

**Comment by rafael5** [comment]
Can you make each one of these nine (9) documents into an issue, and track
in the issue tracker? (with all of the TODO items within each)


Thank you



*Rafael Richards MD MS*
*202-469-1527*

**Comment by rafael5** [comment]
Thank you for this excellent and diligent analysis!

=> I recommend you break each of these 9 documents into a separate issue,
so you can track on the Issue Tracker.


*Rafael Richards MD MS*
*202-469-1527*

**Comment by rafael5** [comment]
=> Convert this into a TABLE so you can record the status of each of these
nine documents...


Rafael


*Rafael Richards MD MS*
*202-469-1527*

**Comment by piyushthesia** [comment]
Yes I will.

**Comment by piyushthesia** [comment]
@rafael5  I have broken the 9 items in their own separate tables. Please review and advise.
https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/ATO/VAM2%20ATO%20Dashboard%20Gap%20Analysis.md

**Comment by rafael5** [comment]
Excellent!

Next:
=> Add an "Assigned to"  column to all the tables, and insert who are
assigned each of these subtasks...



Rafael


*Rafael Richards MD MS*
*202-469-1527*

**Comment by piyushthesia** [comment]
Ok. I'll do it right away

**Comment by piyushthesia** [comment]
@rafael5 Created the Column.  @davidfaulkner08 and @nilesh1402 will have to assign each subtasks.
