### ISSUE TITLE
IOC Dashboard - COMPLETE OVERHAUL

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#27]
https://github.com/vistadataproject/VAM2ProjectManagement#ioc-dashboard

1. Please create a complete, correct IOC dashboard with all VA-required elements based on VA's  policies (VIP, etc)
2. Update dashboard so that IOC is October 1, 2019

**Comment by nilesh1402** [comment]
Updated the dashboard and added the link to IOC Process
