### ISSUE TITLE
SSP - System Security Plan

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#29]
System Security Plan (SSP): ( Plan of completion April 12 ) 
Changes made or are in need of updating:

Change made: Control Owner changed to Christopher Brown
Change made: Authorizing official is now Joseph Fourcade
Update needed: Identify Threats in table 5
Update needed: Update control status, section 2.0
Update needed: Re-review NIST controls to ensure that they are current (Minimal updating likely)
Updated needed: Index needs reformatting

**Comment by davidfaulkner08** [comment]
@rafael5 Most of the updates that can be made at this time have been completed. But since this is a continuously updated document, it won't be complete till likely during Production.

**Comment by saviomendonsa** [comment]
Completed.
