### ISSUE TITLE
SA - Signature Authority

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#30]
Signature Authority: 
Changes made or are in need of updating:

Change made: Updated SO and ISO
Update needed: SO and ISO to sign, pending final SSP.

**Comment by davidfaulkner08** [comment]
@rafael5 SA, has been updated. Will be submitted upon the SSP being at an acceptable completion point. The SSP is a continuously updated document.

**Comment by saviomendonsa** [comment]
Completed.
