### ISSUE TITLE
RA - Risk Assessment

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#31]
Risk Assessment: 
Changes made or are in need of updating:

Change made: changed owner to Christopher Brown
Update needed: Table 1, NIST control families system risks
Update needed: Phone numbers of POCs
Update needed: Secondary ISO
Update needed: Updated Table 5. Risk Assessment Inputs
Update needed: Table 6. Apply Threat source list to SSP. May needed additions in RA.
Update needed: Table 7. Vulnerability list will be updated throughout project cycle. Most current responses required
Update needed: Table 13. Obtain VAM Pen Test, Database scan, PIA signature, signature for DRP, Obtain Secure Design review (Microsoft threat modeling tool), ISCP signature from ISO,

**Comment by davidfaulkner08** [comment]
@rafael5  RA changes and updates made. This document will be reviewed, but a contentiously incomplete document until Production. It will be uploaded to RiskVision despite its completion, as this is still required.

**Comment by saviomendonsa** [comment]
Completed.
