### ISSUE TITLE
CMP - Configuration Management Plan

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#32]
Configuration Management Plan (CMP): 
Changes made or are in need of updating:

Update needed: Figure 1. Update Software Development Environment related to SCM
Update needed: For life of the project, the CMP should be updated by DevOps and/or DevArch and managed additionally by Security and approved by the Project Manager.

**Comment by davidfaulkner08** [comment]
@rafael5 CMP has been sent to you for review.

**Comment by saviomendonsa** [comment]
Completed.
