### ISSUE TITLE
DRP - Disaster Recovery Plan

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#34]
Disaster Recovery Plan (DRP): 
Changes made or are in need of updating:

Change made: Changed SO and ISO. Added POCs.
Update needed: Reformat Distribution table
Update needed: VAM arch diagram needs to be changed
Update needed: DRP Assumptions 1.3. Verify if assumptions are valid or not
Update needed: Appendix A, B & C: Verify if DRP personnel contacts are current

**Comment by davidfaulkner08** [comment]
@rafael5 I'm currently converting to new version and updating. Will be sent for your review, then tech review this week

**Comment by saviomendonsa** [comment]
Completed.
