### ISSUE TITLE
ISA-MOU  -  Interconnection Security Agreement / Memorandum of Understanding

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#36]
Interconnection Security Agreement / Memorandum of Understanding (ISA/MOU): 
Changes made or are in need of updating:

Update needed: Obtain MOU

**Comment by rafael5** [comment]
Where is the MOU?

**Comment by nilesh1402** [comment]
Template is on VA SharePoint and link is maintained under  readme file for Risk Vision Templates : https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/riskvision_templates_2019/readme.md
