### ISSUE TITLE
FYI: new weekly minutes format

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#43]
small change in formatting
re-use for all future meeting minutes

https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/weekly_meeting_minutes/VAM2-Week05-03-19-2019.md

**Comment by piyushthesia** [comment]
Understand.  Will adhere to it. (Following it already for the Technical Deep Dive Meeting Notes)
