### ISSUE TITLE
System Security Categorization - PERSONNEL UPDATE; SIGNATURE

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#51]
System Security Categorization has incorrect and incomplete personnel listed.

Please update with complete and correct personnel listed and obtain signatures.

**Comment by davidfaulkner08** [comment]
@rafael5 Personnel corrected. SSC, sent to you for review before submitting for signatures.

**Comment by saviomendonsa** [comment]
Completed.
