### ISSUE TITLE
ATO Document Tasks as of 2019-04-08

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#52]
ATO Document Tasks as of: 06-28-2019

| Doc | v# | Sig# | SO | PO | PM | ISO | BO | Status |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| BIA | 4 | 2 | SIGNED | N/A | SIGNED | N/A | N/A | DONE |
| CMP | 5 | 3 | SIGNED | N/A | SIGNED | SIGNED |N/A | DONE |
| DRP | 4 | 4 | SIGNED | N/A | SIGNED  | SIGNED | N/A | DONE |
| IRP | - | 2 | SIGNED | N/A | N/A | SIGNED  | N/A | Pending PO Signature|
| ISCP | - | 4 | SIGNED   | N/A | SIGNED   | SIGNED | N/A | DONE |
| MOU | - | N/A | N/A | N/A | N/A | N/A | N/A | N/A |
| PIA | 5 | 3 | SIGNED | SIGNED  | N/A | SIGNED  |N/A | DONE |
| PTA | - | 3 | SIGNED | SIGNED | N/A | N/A | N/A | DONE |
| RA | - | N/A | N/A | N/A | N/A | N/A | N/A | In conjunction with SSP, ISO will begin her final review no later than 06-28-2019 provided we have all signatures by SO, PM, PO, BO, and PIA Support Group. "This is Finalizing RV/Security Controls/All of the ATO Documents Uploaded into RV as Evidence. This shall include Available Scans, and System Boundary.  |
| SIA | 5 | N/A | N/A | N/A | N/A | N/A | N/A | DONE |
| SSC | 6 | 2 | SIGNED  | N/A | N/A | SIGNED | SIGNED | DONE |
| SSP | - | 4 | Not Now | Not Now | Not Now| Not Now | N/A | RISKVISION GENERATED. </br> </br> ISO will begin her final review no later than 06-28-2019 provided we have all signatures by SO, PM, PO, BO, and PIA Support Group. "This is Finalizing RV/Security Controls/All of the ATO Documents Uploaded into RV as Evidence. This shall include Available Scans, and System Boundary.  </br> </br> All will sign after controls are updated |
| SDD | - | N/A | N/A | N/A | N/A | N/A | N/A | Pending Conor review |
| SA | - | 2| Not Now | N/A | N/A | Not Now | N/A | To be Signed AFTER SSP |
| SOA | - | 2 | SIGNED | N/A | N/A | SIGNED | N/A | DONE |
| SOR | - | 1 | SIGNED| N/A | N/A | N/A | N/A | DONE |
| SDR | - | N/A | N/A | N/A | N/A | N/A | N/A | REGISTRATION WITH SWA DONE. THREAT MODEL NOT REQUIRED AS PER PM-ECSO |

**Comment by piyushthesia** [comment]
@rafael5 Updated tracker table.

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
 Updated Table

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 

Dr. Richards I've created the columns you suggested.  Let me know if you need anything else revised or updated please.

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
Updated the signatures by PM

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
Updated the Table and  Added BO Signature Column.

**Comment by piyushthesia** [comment]
@owsleyc41 

Updated Table

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41 

Table Updated

**Comment by piyushthesia** [comment]
Updated Table as of 06-27-2019

@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by saviomendonsa** [comment]
Completed.
