### ISSUE TITLE
ATO Documents Requiring ISO Signature

### ISSUE THREAD

**Issue by piyushthesia** [vistadataproject/VAM2ProjectManagement#54]
## ATO Documents Requiring **ISO**  Signature as of 06-28-2019

| Item # | Document | Date Submitted for Signature | Status |
|:---:|:---|:---:|:---:|
| 1| System Security Plan (SSP) | - | After document is System Generated upon RV Controls update |
| 2 | Signatory Authority (SA) | - | After SSP |
| 3 | Configuration Management Plan (CMP) | - | SIGNED |
| 4 | Incident Response Plan (IRP) | - | SIGNED |
| 5 | Information Security Contingency Plan (ISCP)  | - | SIGNED |
| 6 | Disaster Recovery Plan (DRP) | - | SIGNED |
| 7 | Privacy Impact Assessment (PIA) | - | SIGNED | 
| 8 | SSC - System Security Classification | - | SIGNED |
| 9 | SOA - System Owner Attestation | - | SIGNED |

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 

Updated Table

**Comment by rafael5** [comment]
All these documents required multiple signatures. 
You need separate columns for each signer... To track each signature. Please add these extra fours columsa and track.

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
Updated Table

**Comment by piyushthesia** [comment]
@owsleyc41 

Updated Table

**Comment by piyushthesia** [comment]
Updated Table @rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by piyushthesia** [comment]
Updated Table as of 06-28-2019
@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by saviomendonsa** [comment]
Completed.
