### ISSUE TITLE
ATO Documents Requiring SO Signature

### ISSUE THREAD

**Issue by piyushthesia** [vistadataproject/VAM2ProjectManagement#55]
## ATO Documents Requiring **SO**  Signature as of 06-28-2019

| Item # | Document | Date Submitted for Signature | Status |
|:---:|:---|:---:|:---:|
| 1 | System Security Plan (SSP) | - | After document is System Generated upon RV Controls update|
| 2 | Signatory Authority (SA) | - | After SSP |
| 3 | Configuration Management Plan (CMP) | - | SIGNED |
| 4 | Incident Response Plan (IRP) | - | SIGNED |
| 5 | Information Security Contingency Plan (ISCP)  | - | SIGNED  |
| 6 | Disaster Recovery Plan (DRP) | - | SIGNED |
| 7 | Privacy Impact Assessment (PIA) | - | SIGNED | 
| 8 | SSC - System Security Classification | - | SIGNED |
| 9 | SOA - System Owner Attestation | - | SIGNED |
| 10 | SOR - System Owner Responsibilities  | - | SIGNED |
| 11 | PTA - Privacy Threshold Analysis | - | SIGNED |
| 12 | BIA - Business Impact Analysis | - | SIGNED |

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 

Updated Table

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
Updated Table

**Comment by piyushthesia** [comment]
@owsleyc41 

Updated Table

**Comment by piyushthesia** [comment]
Updated Table with today's status.
@rafael5 @nilesh1402 @owsleyc41 @davidfaulkner08

**Comment by piyushthesia** [comment]
updated table with status as of 06-27-2019
@rafael5 @nilesh1402 @owsleyc41 @davidfaulkner08

**Comment by piyushthesia** [comment]
updated table with status as of 06-28-2019
@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by saviomendonsa** [comment]
Completed.
