### ISSUE TITLE
ATO Documents Requiring PM Signature

### ISSUE THREAD

**Issue by piyushthesia** [vistadataproject/VAM2ProjectManagement#57]
## ATO Documents Requiring **PM**  Signature as of 06-27-2019

| Item # | Document | Date Submitted for Signature | Status |
|:---:|:---|:---:|:---:|
| 1 | System Security Plan (SSP) | - | After document is System Generated upon RV Controls update  |
| 2 | Configuration Management Plan (CMP) | - | SIGNED |
| 3 | Information Security Contingency Plan (ISCP)  | - | SIGNED |
| 4 | Disaster Recovery Plan (DRP) | - | SIGNED |
| 5 | BIA - Business Impact Analysis | - | SIGNED |

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 

Updated Table

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 
Updated the table

**Comment by piyushthesia** [comment]
@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41 

Updated Table

**Comment by piyushthesia** [comment]
Updated Table @rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by piyushthesia** [comment]
Updated Table with status as of 06-27-2019
@rafael5 @nilesh1402 @davidfaulkner08 @owsleyc41

**Comment by piyushthesia** [comment]
Documents signed and updated in RiskVision

**Comment by piyushthesia** [comment]
SSP needs signature

**Comment by saviomendonsa** [comment]
Completed.
