### ISSUE TITLE
Reword AWS Kinesis and AWS CloudWatch 

### ISSUE THREAD

**Issue by davidfaulkner08** [vistadataproject/VAM2ProjectManagement#58]
AWS Kinesis and AWS Cloudwatch need to be be stated as "AWS Kinesis Streams & AWS Cloudwatch Logs" in all documents stating the two. This does not require immediate attention, but these updates must be made in the short-term.

**Comment by rafael5** [comment]
Please cross check these (and not other close wordings) are on the VAEC ATO catalog.

**Comment by saviomendonsa** [comment]
Completed.
