### ISSUE TITLE
Tight timeline for the Capacity, Performance, and Scalability Assessment for National Deployment

### ISSUE THREAD

**Issue by saviomendonsa** [vistadataproject/VAM2ProjectManagement#60]
The delay in going to IOC Prod gives the team a very short time to deliver the Capacity, Performance, and Scalability Assessment for National Deployment. There is a possibility that we may need a no-cost extension of a couple of weeks to complete it.

**Comment by rafael5** [comment]
Correct. We can discuss at the weekly meeting.
