### ISSUE TITLE
VAEC ATO resources

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#7]
SharePoint:   https://vaww.portal.va.gov/sites/ECS/Pages/Cybersecurity-in-the-VAEC.aspx

**Comment by rafael5** [comment]
See also:  https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/ATO/ATO_VAEC_Requirements.md

**Comment by nilesh1402** [comment]
Updated Comparison between OIS SOP  and ATO Cloud process : https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/ATO/ATO%20Process%20Comparison%20for%20VAM%20ver%203.xlsx

**Comment by rafael5** [comment]
Thank you.  Excllent!
