### ISSUE TITLE
Review of the Draft Master Test plan

### ISSUE THREAD

**Issue by nilesh1402** [vistadataproject/VAM2ProjectManagement#8]
Please review the draft Master Test plan. It is due as deliverable on 3/4/2019. Here is the link:
https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/CLIN%200003AA%20Master%20Test%20Plan.docx

**Comment by rafael5** [comment]
nilesh - can you please export this Word document to text and then post the text file as markdown.
When the markdown document content looks correct, we will export it from markdown to Word.

**Comment by rafael5** [comment]
For all updates to document:  edit the markdown version here:
https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/master-test-plan.md

**Comment by rafael5** [comment]
note;  i have removed UAT testing as there are no 'user interface' or  user-facing components to test.  This is a purely a technical / infrastructure / performance testing that is required.  please refer to the pws testing section for details on testing.

**Comment by rafael5** [comment]
Re; Ablevets pipeline: please provide detailed information on what exactly this is, and include in the document. Also include its interfaces / APIs to connect the ablevets tools to the git repository.   no artifacts should be migrated off of the project repository; they need to remain the sole authoritative version.
