### ISSUE TITLE
Complete list of PWS Project Management deliverables

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/VAM2ProjectManagement#9]
Create complete list of all Project Management deliverables and documents, with links to them on the Project Repository.  This is the starting table:

https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/README.md

**Comment by rafael5** [comment]
NB: Please go back to the original Response to the PWS, and create full table of all deliverables.

**Comment by nilesh1402** [comment]
Added all the contract deliverables

**Comment by rafael5** [comment]
Please provide a link to the PWS tasks in markdown table..

I do not see the PWS Dashboard with any new tasks...

**Comment by rafael5** [comment]
Where are the PWS tasks listed?  They should be on the PWS Dashboard table here:
https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/README.md

**Comment by piyushthesia** [comment]
Updated the Links to PWS deliverables, where applicable.

**Comment by piyushthesia** [comment]
Link to Technical Kickoff Meeting Notes:  https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/source/VAM2_Technical_Kickoff_Meeting_Notes_20190206.md

Link to CPMP:  https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/source/VAM2_CLIN%200001AA_Contractor_Project_Management_Plan_20190304.docx

Link to Monthly Progress Report:  https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/source/VAM2_CLIN0001AB_Monthly_Progress_Report_20190304.docx

Link to Master Test Plan:  https://github.com/vistadataproject/VAM2ProjectManagement/blob/master/Documents/pws/Master_Test_Plan.md

**Comment by piyushthesia** [comment]
Done.
